### ISSUE TITLE
No constructor 'GetMaterialApp.' with matching arguments declared in class 'GetMaterialApp'.

### ISSUE THREAD

**Issue by moxun33** [CNAD666/flutter_use#2]
build windows应用时，修改代码后hot reload报错

# Flutter版本

` Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)
`
# 详细错误

```js
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building MyApp(dirty):
No constructor 'GetMaterialApp.' with matching arguments declared in class 'GetMaterialApp'.
Receiver: GetMaterialApp
Tried calling: new GetMaterialApp.()
Found: new GetMaterialApp.({Key? key, GlobalKey<NavigatorState>? navigatorKey, Widget? home, Map<String, (BuildContext) => Widget> routes, String? initialRoute, ((RouteSettings) => Route<dynamic>?)? onGenerateRoute, ((String) => List<Route<dynamic>>)? onGenerateInitialRoutes, ((RouteSettings) => Route<dynamic>?)? onUnknownRoute, List<NavigatorObserver> navigatorObservers, ((BuildContext, Widget?) => Widget)? builder, TextDirection? textDirection, String title, ((BuildContext) => String)? onGenerateTitle, Color? color, ThemeData? theme, ThemeData? darkTheme, ThemeMode themeMode, Locale? locale, Locale? fallbackLocale, Iterable<LocalizationsDelegate<dynamic>>? localizationsDelegates, ((List<Locale>?, Iterable<Locale>) => Locale?)? localeListResolutionCallback, ((Locale?, Iterable<Locale>) => Locale?)? localeResolutionCallback, Iterable<Locale> supportedLocales, bool debugShowMaterialGrid, bool showPerformanceOverlay, bool checkerboardRasterCacheImages, bool checkerboardOffscreenLayers, bool showSemanticsDebugger, bool debugShowCheckedModeBanner, Map<LogicalKeySet, Intent>? shortcuts, CustomTransition? customTransition, Map<String, Map<String, String>>? translationsKeys, Translations? translations, (() => void)? onInit, (() => void)? onReady, (() => void)? onDispose, ((Routing?) => void)? routingCallback, Transition? defaultTransition, List<GetPage<dynamic>>? getPages, bool? opaqueRoute, bool? enableLog, ((String, {bool isError}) => void)? logWriterCallback, bool? popGesture, Duration? transitionDuration, bool? defaultGlobalState, SmartManagement smartManagement, Bindings? initialBinding, GetPage<dynamic>? unknownRoute, ThemeData? highContrastTheme, ThemeData? highContrastDarkTheme, Map<Type, Action<Intent>>? actions}) => GetMaterialApp

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
When the exception was thrown, this was the stack: 
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:212:5)
#1      MyApp.build (package:flutter_use/main.dart)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
...
====================================================================================================
```

**Comment by xdd666t** [comment]
这种情况，确实存在，在编译web或者windows之类热加载的时候，都可能产生GetMaterialApp报错
一般解决方法：**重新运行下**
兄弟，你可以给GetX提个issue，这个我也不造怎么根源上解决：https://github.com/jonataslaw/getx/issues

**Comment by moxun33** [comment]
> 这种情况，确实存在，在编译web或者windows之类热加载的时候，都可能产生GetMaterialApp报错
> 一般解决方法：**重新运行下**
> 兄弟，你可以给GetX提个issue，这个我也不造怎么根源上解决：https://github.com/jonataslaw/getx/issues

感谢大佬!
